export const config = {
  supabaseUrl: Deno.env.get("SUPABASE_URL") ?? "",
  supabaseServiceRoleKey: Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
  tokenEncryptionKey: Deno.env.get("TOKEN_ENCRYPTION_KEY") ?? "",
  cronVerifySecret: Deno.env.get("SUPABASE_CRON_VERIFY_SECRET") ?? "",
  googleClientId: Deno.env.get("GOOGLE_CLIENT_ID") ?? "",
  googleClientSecret: Deno.env.get("GOOGLE_CLIENT_SECRET") ?? "",
  microsoftClientId: Deno.env.get("MICROSOFT_CLIENT_ID") ?? "",
  microsoftClientSecret: Deno.env.get("MICROSOFT_CLIENT_SECRET") ?? "",
  microsoftTenantId: Deno.env.get("MICROSOFT_TENANT_ID") ?? "",
  hubspotClientId: Deno.env.get("HUBSPOT_CLIENT_ID") ?? "",
  hubspotClientSecret: Deno.env.get("HUBSPOT_CLIENT_SECRET") ?? "",
  salesforceClientId: Deno.env.get("SALESFORCE_CLIENT_ID") ?? "",
  salesforceClientSecret: Deno.env.get("SALESFORCE_CLIENT_SECRET") ?? "",
  salesforceAuthBaseUrl: Deno.env.get("SALESFORCE_AUTH_BASE_URL") ?? "https://login.salesforce.com",
  followUpDelayDays: Number(Deno.env.get("FOLLOW_UP_DELAY_DAYS") ?? "2"),
  defaultPerMinuteThrottle: Number(Deno.env.get("DEFAULT_PER_MINUTE_THROTTLE") ?? "10"),
  seedMonitorIntervalMinutes: Number(Deno.env.get("SEED_MONITOR_INTERVAL_MINUTES") ?? "30"),
};
