export const creatorCopy = {
  start: {
    createTitle: "Create a new campaign",
    editTitle: "Update the campaign setup",
    description: "Start from a proven template or build a fresh message in minutes.",
    scratchTitle: "Start from scratch",
    scratchDescription:
      "Begin with a plain-text email and a simple follow-up you can shape as you go.",
    templateTitle: "Use a template",
    templateDescription:
      "Pick a saved or default template and make it yours before launch.",
    campaignNameLabel: "Campaign name",
    campaignNamePlaceholder: "Q2 partnership outreach",
    senderLabel: "Sender mailbox",
    senderEmptyLabel: "No approved sender connected yet",
    senderHelperTitle: "Connect a sender before launch",
    senderHelperBody: "This project needs a connected mailbox before emails can go out.",
    senderHelperCta: "Open Settings",
    templateDialogTitle: "Choose a starting template",
    templateDialogDescription:
      "Select a template to preload your first email. You can still edit every line before launch.",
    templateSearchPlaceholder: "Search templates by name or subject",
    templateSelectLabel: "Use template",
    templateEmptyTitle: "No templates available yet",
    templateEmptyDescription:
      "Create a template first, or start this campaign from scratch.",
  },
  audience: {
    title: "Choose who should get this campaign",
    description: "Search, select, or add contacts without leaving the campaign.",
    searchPlaceholder: "Search by email, name, company, title, or tag",
    selectedCount: (count: number) => `${count} selected`,
    selectVisible: "Select visible",
    clearSelection: "Clear",
    importContacts: "Import contacts",
    addContact: "Add contact",
    addContactTitle: "Add a contact",
    empty: "No contacts yet. Import a list or add one contact to get started.",
    noMatches: "No contacts match this search yet.",
    continueError: "Select at least one contact to continue.",
  },
  message: {
    title: "Write the emails people will actually reply to",
    description: "Start simple. Add more branching only if this campaign needs it.",
    primaryLabel: "Email 1",
    primaryDescription: "Lead with a clear reason to reply.",
    followUpLabel: "Follow-up",
    followUpDescription: "A short, polite nudge that feels human.",
    changeTemplate: "Change template",
    switchToHtml: "Switch to designed email",
    switchToText: "Switch back to plain text",
    writeTab: "Write",
    previewTab: "Preview",
    subjectLabel: "Subject",
    bodyLabel: "Body",
    htmlBodyLabel: "Designed email HTML",
    importHtmlLabel: "Import HTML file",
    previewSubjectLabel: "Preview subject",
    previewBodyLabel: "Preview body",
    sendImmediately: "Starts when launched",
    sendAfter: (days: number) => `Sends after ${days} day${days === 1 ? "" : "s"}`,
    advancedLabel: "Customize the sequence",
    advancedDescription:
      "Add more steps or branching rules without crowding the main composer.",
    advancedAddStep: "Add a step",
    advancedLimit: "Up to 5 steps",
    advancedExtraStepHelper: "Extra steps can be fully edited here.",
    routeMatchLabel: "If condition matches",
    routeNoMatchLabel: "If condition does not match",
    routeDelayLabel: "Delay before next action",
    routeNameLabel: "Step name",
    routeBranchLabel: "Check for",
    nextStepLabel: "Continue to next step",
    exitLabel: "Stop the sequence",
    timeLabel: "Delay only",
    openedLabel: "Email opened",
    clickedLabel: "Link clicked",
  },
  review: {
    title: "Review before launch",
    sectionTitle: "Everything looks ready",
    description: "Your campaign will start sending during your selected send window.",
    senderLabel: "Sender",
    audienceLabel: "Audience",
    sequenceLabel: "Sequence",
    scheduleLabel: "Send window",
    dailyCapLabel: "Daily cap",
    timezoneLabel: "Timezone",
    timezonePlaceholder: "Asia/Calcutta",
    sendWindowLabel: "Send window",
    presetLabel: "Quick presets",
    customLabel: "Custom hours",
    launchLabel: "Launch campaign",
    launchNowLabel: "Launch and send first batch",
    saveChangesLabel: "Save changes",
    checklistTitle: "Pre-launch checklist",
    sequenceSummary: (count: number) => `${count} email${count === 1 ? "" : "s"} in this sequence`,
  },
  nav: {
    back: "Back",
    continue: "Continue",
  },
  summary: {
    title: "Campaign summary",
    starterLabel: "Starter",
    senderLabel: "Sender",
    contactsLabel: "Selected contacts",
    subjectLabel: "Primary subject",
    followUpDelayLabel: "Follow-up delay",
    sendWindowLabel: "Send window",
    dailyCapLabel: "Daily cap",
    sequenceLabel: "Sequence",
    templateStarter: "Template",
    scratchStarter: "Start from scratch",
    noTemplateSelected: "No template selected",
    noSender: "Sender needed",
    noSubject: "Needs subject",
    change: "Change",
    senderReady: "Sender ready",
    contactsReady: (count: number) => `${count} contact${count === 1 ? "" : "s"} selected`,
    subjectReady: "Primary email ready",
  },
  toasts: {
    launchError: "Failed to launch campaign",
    updateError: "Failed to update campaign",
    updated: "Campaign updated",
    launched: "Campaign launched",
    launchedAndSent: (processed: number) =>
      `Campaign launched and sent to ${processed} contact${processed === 1 ? "" : "s"}.`,
    launchedNoReadyContacts: "Campaign launched. No contacts were ready to send yet.",
    sendNowFailed: "Campaign created, but send now failed",
    missingCampaignId: "Campaign was saved without a valid ID.",
    templateApplied: (name: string) => `Loaded ${name}`,
  },
} as const;

export const commonTimezoneOptions = [
  "Asia/Calcutta",
  "UTC",
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "Europe/London",
  "Europe/Berlin",
  "Europe/Paris",
  "Europe/Madrid",
  "Asia/Dubai",
  "Asia/Singapore",
  "Asia/Tokyo",
  "Australia/Sydney",
] as const;
